/**
 * This class is generated by jOOQ
 */
package org.lobobrowser.db;

/**
 * A class modelling foreign key relationships between tables of the
 * <code>PUBLIC</code> schema
 */
@javax.annotation.Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.5.0"
    },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final org.jooq.UniqueKey<org.lobobrowser.db.tables.records.PermissionsRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
  public static final org.jooq.UniqueKey<org.lobobrowser.db.tables.records.CookiesRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
  public static final org.jooq.UniqueKey<org.lobobrowser.db.tables.records.GlobalsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
    public static final org.jooq.UniqueKey<org.lobobrowser.db.tables.records.PermissionsRecord> CONSTRAINT_C = createUniqueKey(
        org.lobobrowser.db.tables.Permissions.PERMISSIONS, org.lobobrowser.db.tables.Permissions.PERMISSIONS.FRAMEHOST,
        org.lobobrowser.db.tables.Permissions.PERMISSIONS.REQUESTHOST);
    public static final org.jooq.UniqueKey<org.lobobrowser.db.tables.records.CookiesRecord> CONSTRAINT_6 = createUniqueKey(
        org.lobobrowser.db.tables.Cookies.COOKIES, org.lobobrowser.db.tables.Cookies.COOKIES.HOSTNAME, org.lobobrowser.db.tables.Cookies.COOKIES.NAME);
    public static final org.jooq.UniqueKey<org.lobobrowser.db.tables.records.GlobalsRecord> CONSTRAINT_3 = createUniqueKey(
        org.lobobrowser.db.tables.Globals.GLOBALS, org.lobobrowser.db.tables.Globals.GLOBALS.NOTACOLUMN);
  }
}
