/**
 * This class is generated by jOOQ
 */
package org.lobobrowser.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.5.0"
    },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Globals extends org.jooq.impl.TableImpl<org.lobobrowser.db.tables.records.GlobalsRecord> {

  private static final long serialVersionUID = 418901589;

  /**
   * The reference instance of <code>PUBLIC.GLOBALS</code>
   */
  public static final org.lobobrowser.db.tables.Globals GLOBALS = new org.lobobrowser.db.tables.Globals();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<org.lobobrowser.db.tables.records.GlobalsRecord> getRecordType() {
    return org.lobobrowser.db.tables.records.GlobalsRecord.class;
  }

  /**
   * The column <code>PUBLIC.GLOBALS.NOTACOLUMN</code>.
   */
  public final org.jooq.TableField<org.lobobrowser.db.tables.records.GlobalsRecord, String> NOTACOLUMN = createField("NOTACOLUMN",
      org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

  /**
   * The column <code>PUBLIC.GLOBALS.SCHEMAVERSION</code>.
   */
  public final org.jooq.TableField<org.lobobrowser.db.tables.records.GlobalsRecord, Integer> SCHEMAVERSION = createField(
      "SCHEMAVERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
   * The column <code>PUBLIC.GLOBALS.PERMISSIONSINITIALIZED</code>.
   */
  public final org.jooq.TableField<org.lobobrowser.db.tables.records.GlobalsRecord, Boolean> PERMISSIONSINITIALIZED = createField(
      "PERMISSIONSINITIALIZED", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

  /**
   * Create a <code>PUBLIC.GLOBALS</code> table reference
   */
  public Globals() {
    this("GLOBALS", null);
  }

  /**
   * Create an aliased <code>PUBLIC.GLOBALS</code> table reference
   */
  public Globals(final String alias) {
    this(alias, org.lobobrowser.db.tables.Globals.GLOBALS);
  }

  private Globals(final String alias, final org.jooq.Table<org.lobobrowser.db.tables.records.GlobalsRecord> aliased) {
    this(alias, aliased, null);
  }

  private Globals(final String alias, final org.jooq.Table<org.lobobrowser.db.tables.records.GlobalsRecord> aliased,
      final org.jooq.Field<?>[] parameters) {
    super(alias, org.lobobrowser.db.Public.PUBLIC, aliased, parameters, "");
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.UniqueKey<org.lobobrowser.db.tables.records.GlobalsRecord> getPrimaryKey() {
    return org.lobobrowser.db.Keys.CONSTRAINT_3;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.util.List<org.jooq.UniqueKey<org.lobobrowser.db.tables.records.GlobalsRecord>> getKeys() {
    return java.util.Arrays.<org.jooq.UniqueKey<org.lobobrowser.db.tables.records.GlobalsRecord>> asList(org.lobobrowser.db.Keys.CONSTRAINT_3);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.lobobrowser.db.tables.Globals as(final String alias) {
    return new org.lobobrowser.db.tables.Globals(alias, this);
  }

  /**
   * Rename this table
   */
  public org.lobobrowser.db.tables.Globals rename(final String name) {
    return new org.lobobrowser.db.tables.Globals(name, null);
  }
}
